use serde::{Deserialize, Serialize};
use std::collections::HashMap;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct Opcode(pub u8);

impl Opcode {
    pub const STOP: Opcode = Opcode(0x00);
    pub const ADD: Opcode = Opcode(0x01);
    pub const MUL: Opcode = Opcode(0x02);
    pub const SUB: Opcode = Opcode(0x03);
    pub const DIV: Opcode = Opcode(0x04);
    pub const SDIV: Opcode = Opcode(0x05);
    pub const MOD: Opcode = Opcode(0x06);
    pub const SMOD: Opcode = Opcode(0x07);
    pub const ADDMOD: Opcode = Opcode(0x08);
    pub const MULMOD: Opcode = Opcode(0x09);
    pub const EXP: Opcode = Opcode(0x0a);
    pub const SIGNEXTEND: Opcode = Opcode(0x0b);
    
    pub const LT: Opcode = Opcode(0x10);
    pub const GT: Opcode = Opcode(0x11);
    pub const SLT: Opcode = Opcode(0x12);
    pub const SGT: Opcode = Opcode(0x13);
    pub const EQ: Opcode = Opcode(0x14);
    pub const ISZERO: Opcode = Opcode(0x15);
    pub const AND: Opcode = Opcode(0x16);
    pub const OR: Opcode = Opcode(0x17);
    pub const XOR: Opcode = Opcode(0x18);
    pub const NOT: Opcode = Opcode(0x19);
    pub const BYTE: Opcode = Opcode(0x1a);
    pub const SHL: Opcode = Opcode(0x1b);
    pub const SHR: Opcode = Opcode(0x1c);
    pub const SAR: Opcode = Opcode(0x1d);
    
    pub const SHA3: Opcode = Opcode(0x20);
    
    pub const ADDRESS: Opcode = Opcode(0x30);
    pub const BALANCE: Opcode = Opcode(0x31);
    pub const ORIGIN: Opcode = Opcode(0x32);
    pub const CALLER: Opcode = Opcode(0x33);
    pub const CALLVALUE: Opcode = Opcode(0x34);
    pub const CALLDATALOAD: Opcode = Opcode(0x35);
    pub const CALLDATASIZE: Opcode = Opcode(0x36);
    pub const CALLDATACOPY: Opcode = Opcode(0x37);
    pub const CODESIZE: Opcode = Opcode(0x38);
    pub const CODECOPY: Opcode = Opcode(0x39);
    pub const GASPRICE: Opcode = Opcode(0x3a);
    pub const EXTCODESIZE: Opcode = Opcode(0x3b);
    pub const EXTCODECOPY: Opcode = Opcode(0x3c);
    pub const RETURNDATASIZE: Opcode = Opcode(0x3d);
    pub const RETURNDATACOPY: Opcode = Opcode(0x3e);
    pub const EXTCODEHASH: Opcode = Opcode(0x3f);
    
    pub const BLOCKHASH: Opcode = Opcode(0x40);
    pub const COINBASE: Opcode = Opcode(0x41);
    pub const TIMESTAMP: Opcode = Opcode(0x42);
    pub const NUMBER: Opcode = Opcode(0x43);
    pub const DIFFICULTY: Opcode = Opcode(0x44);
    pub const GASLIMIT: Opcode = Opcode(0x45);
    pub const CHAINID: Opcode = Opcode(0x46);
    pub const SELFBALANCE: Opcode = Opcode(0x47);
    pub const BASEFEE: Opcode = Opcode(0x48);
    
    pub const POP: Opcode = Opcode(0x50);
    pub const MLOAD: Opcode = Opcode(0x51);
    pub const MSTORE: Opcode = Opcode(0x52);
    pub const MSTORE8: Opcode = Opcode(0x53);
    pub const SLOAD: Opcode = Opcode(0x54);
    pub const SSTORE: Opcode = Opcode(0x55);
    pub const JUMP: Opcode = Opcode(0x56);
    pub const JUMPI: Opcode = Opcode(0x57);
    pub const PC: Opcode = Opcode(0x58);
    pub const MSIZE: Opcode = Opcode(0x59);
    pub const GAS: Opcode = Opcode(0x5a);
    pub const JUMPDEST: Opcode = Opcode(0x5b);
    
    pub const PUSH0: Opcode = Opcode(0x5f);
    pub const PUSH1: Opcode = Opcode(0x60);
    pub const PUSH2: Opcode = Opcode(0x61);
    pub const PUSH3: Opcode = Opcode(0x62);
    pub const PUSH4: Opcode = Opcode(0x63);
    pub const PUSH5: Opcode = Opcode(0x64);
    pub const PUSH6: Opcode = Opcode(0x65);
    pub const PUSH7: Opcode = Opcode(0x66);
    pub const PUSH8: Opcode = Opcode(0x67);
    pub const PUSH9: Opcode = Opcode(0x68);
    pub const PUSH10: Opcode = Opcode(0x69);
    pub const PUSH11: Opcode = Opcode(0x6a);
    pub const PUSH12: Opcode = Opcode(0x6b);
    pub const PUSH13: Opcode = Opcode(0x6c);
    pub const PUSH14: Opcode = Opcode(0x6d);
    pub const PUSH15: Opcode = Opcode(0x6e);
    pub const PUSH16: Opcode = Opcode(0x6f);
    pub const PUSH17: Opcode = Opcode(0x70);
    pub const PUSH18: Opcode = Opcode(0x71);
    pub const PUSH19: Opcode = Opcode(0x72);
    pub const PUSH20: Opcode = Opcode(0x73);
    pub const PUSH21: Opcode = Opcode(0x74);
    pub const PUSH22: Opcode = Opcode(0x75);
    pub const PUSH23: Opcode = Opcode(0x76);
    pub const PUSH24: Opcode = Opcode(0x77);
    pub const PUSH25: Opcode = Opcode(0x78);
    pub const PUSH26: Opcode = Opcode(0x79);
    pub const PUSH27: Opcode = Opcode(0x7a);
    pub const PUSH28: Opcode = Opcode(0x7b);
    pub const PUSH29: Opcode = Opcode(0x7c);
    pub const PUSH30: Opcode = Opcode(0x7d);
    pub const PUSH31: Opcode = Opcode(0x7e);
    pub const PUSH32: Opcode = Opcode(0x7f);
    
    pub const DUP1: Opcode = Opcode(0x80);
    pub const DUP2: Opcode = Opcode(0x81);
    pub const DUP3: Opcode = Opcode(0x82);
    pub const DUP4: Opcode = Opcode(0x83);
    pub const DUP5: Opcode = Opcode(0x84);
    pub const DUP6: Opcode = Opcode(0x85);
    pub const DUP7: Opcode = Opcode(0x86);
    pub const DUP8: Opcode = Opcode(0x87);
    pub const DUP9: Opcode = Opcode(0x88);
    pub const DUP10: Opcode = Opcode(0x89);
    pub const DUP11: Opcode = Opcode(0x8a);
    pub const DUP12: Opcode = Opcode(0x8b);
    pub const DUP13: Opcode = Opcode(0x8c);
    pub const DUP14: Opcode = Opcode(0x8d);
    pub const DUP15: Opcode = Opcode(0x8e);
    pub const DUP16: Opcode = Opcode(0x8f);
    
    pub const SWAP1: Opcode = Opcode(0x90);
    pub const SWAP2: Opcode = Opcode(0x91);
    pub const SWAP3: Opcode = Opcode(0x92);
    pub const SWAP4: Opcode = Opcode(0x93);
    pub const SWAP5: Opcode = Opcode(0x94);
    pub const SWAP6: Opcode = Opcode(0x95);
    pub const SWAP7: Opcode = Opcode(0x96);
    pub const SWAP8: Opcode = Opcode(0x97);
    pub const SWAP9: Opcode = Opcode(0x98);
    pub const SWAP10: Opcode = Opcode(0x99);
    pub const SWAP11: Opcode = Opcode(0x9a);
    pub const SWAP12: Opcode = Opcode(0x9b);
    pub const SWAP13: Opcode = Opcode(0x9c);
    pub const SWAP14: Opcode = Opcode(0x9d);
    pub const SWAP15: Opcode = Opcode(0x9e);
    pub const SWAP16: Opcode = Opcode(0x9f);
    
    pub const LOG0: Opcode = Opcode(0xa0);
    pub const LOG1: Opcode = Opcode(0xa1);
    pub const LOG2: Opcode = Opcode(0xa2);
    pub const LOG3: Opcode = Opcode(0xa3);
    pub const LOG4: Opcode = Opcode(0xa4);
    
    pub const CREATE: Opcode = Opcode(0xf0);
    pub const CALL: Opcode = Opcode(0xf1);
    pub const CALLCODE: Opcode = Opcode(0xf2);
    pub const RETURN: Opcode = Opcode(0xf3);
    pub const DELEGATECALL: Opcode = Opcode(0xf4);
    pub const CREATE2: Opcode = Opcode(0xf5);
    pub const STATICCALL: Opcode = Opcode(0xfa);
    pub const REVERT: Opcode = Opcode(0xfd);
    pub const INVALID: Opcode = Opcode(0xfe);
    pub const SELFDESTRUCT: Opcode = Opcode(0xff);
}

pub fn opcode_map() -> HashMap<&'static str, Opcode> {
    let mut map = HashMap::new();
    map.insert("stop", Opcode::STOP);
    map.insert("add", Opcode::ADD);
    map.insert("mul", Opcode::MUL);
    map.insert("sub", Opcode::SUB);
    map.insert("div", Opcode::DIV);
    map.insert("sdiv", Opcode::SDIV);
    map.insert("mod", Opcode::MOD);
    map.insert("smod", Opcode::SMOD);
    map.insert("addmod", Opcode::ADDMOD);
    map.insert("mulmod", Opcode::MULMOD);
    map.insert("exp", Opcode::EXP);
    map.insert("signextend", Opcode::SIGNEXTEND);
    map.insert("lt", Opcode::LT);
    map.insert("gt", Opcode::GT);
    map.insert("slt", Opcode::SLT);
    map.insert("sgt", Opcode::SGT);
    map.insert("eq", Opcode::EQ);
    map.insert("iszero", Opcode::ISZERO);
    map.insert("and", Opcode::AND);
    map.insert("or", Opcode::OR);
    map.insert("xor", Opcode::XOR);
    map.insert("not", Opcode::NOT);
    map.insert("byte", Opcode::BYTE);
    map.insert("shl", Opcode::SHL);
    map.insert("shr", Opcode::SHR);
    map.insert("sar", Opcode::SAR);
    map.insert("sha3", Opcode::SHA3);
    map.insert("keccak256", Opcode::SHA3);
    map.insert("address", Opcode::ADDRESS);
    map.insert("balance", Opcode::BALANCE);
    map.insert("origin", Opcode::ORIGIN);
    map.insert("caller", Opcode::CALLER);
    map.insert("callvalue", Opcode::CALLVALUE);
    map.insert("calldataload", Opcode::CALLDATALOAD);
    map.insert("calldatasize", Opcode::CALLDATASIZE);
    map.insert("calldatacopy", Opcode::CALLDATACOPY);
    map.insert("codesize", Opcode::CODESIZE);
    map.insert("codecopy", Opcode::CODECOPY);
    map.insert("gasprice", Opcode::GASPRICE);
    map.insert("extcodesize", Opcode::EXTCODESIZE);
    map.insert("extcodecopy", Opcode::EXTCODECOPY);
    map.insert("returndatasize", Opcode::RETURNDATASIZE);
    map.insert("returndatacopy", Opcode::RETURNDATACOPY);
    map.insert("extcodehash", Opcode::EXTCODEHASH);
    map.insert("blockhash", Opcode::BLOCKHASH);
    map.insert("coinbase", Opcode::COINBASE);
    map.insert("timestamp", Opcode::TIMESTAMP);
    map.insert("number", Opcode::NUMBER);
    map.insert("difficulty", Opcode::DIFFICULTY);
    map.insert("prevrandao", Opcode::DIFFICULTY);
    map.insert("gaslimit", Opcode::GASLIMIT);
    map.insert("chainid", Opcode::CHAINID);
    map.insert("selfbalance", Opcode::SELFBALANCE);
    map.insert("basefee", Opcode::BASEFEE);
    map.insert("pop", Opcode::POP);
    map.insert("mload", Opcode::MLOAD);
    map.insert("mstore", Opcode::MSTORE);
    map.insert("mstore8", Opcode::MSTORE8);
    map.insert("sload", Opcode::SLOAD);
    map.insert("sstore", Opcode::SSTORE);
    map.insert("jump", Opcode::JUMP);
    map.insert("jumpi", Opcode::JUMPI);
    map.insert("pc", Opcode::PC);
    map.insert("msize", Opcode::MSIZE);
    map.insert("gas", Opcode::GAS);
    map.insert("jumpdest", Opcode::JUMPDEST);
    map.insert("push0", Opcode::PUSH0);
    map.insert("dup1", Opcode::DUP1);
    map.insert("dup2", Opcode::DUP2);
    map.insert("dup3", Opcode::DUP3);
    map.insert("dup4", Opcode::DUP4);
    map.insert("dup5", Opcode::DUP5);
    map.insert("dup6", Opcode::DUP6);
    map.insert("dup7", Opcode::DUP7);
    map.insert("dup8", Opcode::DUP8);
    map.insert("dup9", Opcode::DUP9);
    map.insert("dup10", Opcode::DUP10);
    map.insert("dup11", Opcode::DUP11);
    map.insert("dup12", Opcode::DUP12);
    map.insert("dup13", Opcode::DUP13);
    map.insert("dup14", Opcode::DUP14);
    map.insert("dup15", Opcode::DUP15);
    map.insert("dup16", Opcode::DUP16);
    map.insert("swap1", Opcode::SWAP1);
    map.insert("swap2", Opcode::SWAP2);
    map.insert("swap3", Opcode::SWAP3);
    map.insert("swap4", Opcode::SWAP4);
    map.insert("swap5", Opcode::SWAP5);
    map.insert("swap6", Opcode::SWAP6);
    map.insert("swap7", Opcode::SWAP7);
    map.insert("swap8", Opcode::SWAP8);
    map.insert("swap9", Opcode::SWAP9);
    map.insert("swap10", Opcode::SWAP10);
    map.insert("swap11", Opcode::SWAP11);
    map.insert("swap12", Opcode::SWAP12);
    map.insert("swap13", Opcode::SWAP13);
    map.insert("swap14", Opcode::SWAP14);
    map.insert("swap15", Opcode::SWAP15);
    map.insert("swap16", Opcode::SWAP16);
    map.insert("log0", Opcode::LOG0);
    map.insert("log1", Opcode::LOG1);
    map.insert("log2", Opcode::LOG2);
    map.insert("log3", Opcode::LOG3);
    map.insert("log4", Opcode::LOG4);
    map.insert("create", Opcode::CREATE);
    map.insert("call", Opcode::CALL);
    map.insert("callcode", Opcode::CALLCODE);
    map.insert("return", Opcode::RETURN);
    map.insert("delegatecall", Opcode::DELEGATECALL);
    map.insert("create2", Opcode::CREATE2);
    map.insert("staticcall", Opcode::STATICCALL);
    map.insert("revert", Opcode::REVERT);
    map.insert("invalid", Opcode::INVALID);
    map.insert("selfdestruct", Opcode::SELFDESTRUCT);
    map
}
